logoText = "🥥 Blog"
logoType = "short" # long, short
description = "The site of Coconut's Blog"
custom_css = ["css/my.css", "css/fonts-zh.css", "css/fonts-code.css", "fontawesome/css/all.css", "css/pace.css"]
custom_js = ["js/pace.min.js"]
useFaviconGenerator = true # https://www.favicon-generator.org/
meta_image = ""
themecolor = ""

themeOptions = ["dark", "light", "solarized"] # dark, light, solarized, hacker, kimbie
notAllowedTypesInHome = ["contact", "talks", "about", "showcase", "publication", "presentation", "resume"]
notAllowedTypesInHomeSidebar = ["about", "archive", "showcase", "publication", "presentation", "resume"]
notAllowedTypesInArchive = ["about", "talks", "showcase", "publication", "presentation", "resume"]
notAllowedTypesInHomeFeed = ["about", "archive", "contact", "talks", "showcase", "publication", "presentation", "resume", "gallery"]

viewportSize = "normal" # widest, wider, wide, normal, narrow
enableUiAnimation = true
hideSingleContentsWhenJSDisabled = false
enablePinnedPosts = true
minItemsToShowInTagCloud = 1 # Minimum items to show in tag cloud

# appbar
enableAppbarSearchIcon = true
enableAppbarLangIcon = false

# header
homeHeaderType = "typewriter" # text, img, slide, typewriter
hideHomeHeaderWhenMobile = false

# menu
showMobileMenuTerms = ["tags", "categories", "series"]

# search
enableSearch = true
enableSearchHighlight = true
searchResultPosition = "side" # side, main
searchContent = true # include content to search index
searchDistance = 100 # fuse option
searchThreshold = 0.4 # 0.0: exact match, 1.0: any match

# body
enableBreadcrumb = false
enableGoToTop = true
enableWhoami = true
summaryShape = "classic" # card, classic, compact
archiveGroupByDate = "2006" # "2006-01": group by month, "2006": group by year
archivePaginate = 13
paginateWindow = 1
talksPaginate = 5
talksGroupByDate = "2006"
pubPaginate = 20
writtenTimeIcon = "📅"
modifiedTimeIcon = "📝"
readingTimeIcon = "☕"
authorIcon = "✍️"
pagePvIcon = "👀"
pinIcon = "📌"
tagIcon = "🏷️"
publicationIcon = "📚"
typeIcon = "🎯"

# whoami
myname = "Coconut🥥"
email = "sherlockx21@163.com"
whoami = "The road is far away, but you are worth it."
bioImageUrl = "https://sherlockblogpic-1314274876.cos.ap-shanghai.myqcloud.com/zzoblog/avatar.jpg?q-sign-algorithm=sha1&q-ak=AKIDey4Ra00sHrG-TyLyqafRyTzQ207MRt6XMVSsKSXiak3QR8V9NEiJVV16kxcTz-gY&q-sign-time=1695061608;1695065208&q-key-time=1695061608;1695065208&q-header-list=host&q-url-param-list=ci-process&q-signature=604778580330abe0ae5819c5aed09417733fd72e&x-cos-security-token=cf2ZKYvBZnyd6MhqEdbPGmhcDdcGULya84d4ee08615611a76058739cf9063e46Ai-g8sbk1J3yP4Ov-R5ZCb34Wf2HR8xAr6oinSxfwkC155USx0b2ymlsdz8GDrSJbKHOEdvcqSGkF1WHCl4FnN3EgHdg884omvfD8VoUYJXgHMgNVR74qReNDZhK28C6ksNX9fihyNFpxqAi_xZija0UeLhxLpOBD6E-Od7XiTDOKufPwiNisRVTdT0jiS9Y&ci-process=originImage"
useGravatar = false
location = "Hangzhou,Zhejiang,China"
organization = "HDU"
link = ""

# sidebar
enableBio = true
enableBioImage = true
enableSidebar = true
enableSidebarTags = true
enableSidebarSeries = true
enableSidebarCategories = true
enableHomeSidebarTitles = false
enableListSidebarTitles = true
enableToc = true
hideToc = false
tocFolding = true
tocPosition = "outer" # inner, outer
enableTocSwitch = true
itemsPerCategory = 5
sidebarPosition = "right"
tocLevels = ["h2", "h3", "h4", "h5", "h6"]
enableSidebarPostsByOrder = false

# footer
showPoweredBy = true
showFeedLinks = true
showSocialLinks = true
enableLangChange = false
enableThemeChange = true

# service
googleTagManager = "" # GTM-XXXXXX
baiduAnalytics = ""
enableBusuanzi = true
busuanziSiteUV = true
busuanziSitePV = true
busuanziPagePV = true

# rss
updatePeriod = "daily" # Possible values: 'hourly', 'daily', 'weekly', 'monthly', or 'yearly'.
updateFrequency = ""
fullContents = true
rssLimit = 10

# comment
enableComment = true
disqus_shortname = ""
commento = false

[telegram]
  enable = false
  siteId = ""
  dataLimit = 5

[gitment]          # Gitment is a comment system based on GitHub issues. see https://github.com/imsun/gitment
  owner = ""              # Your GitHub ID
  repo = ""               # The repo to store comments
  clientId = ""           # Your client ID
  clientSecret = ""       # Your client secret

[utterances]       # https://utteranc.es/
  owner = ""              # Your GitHub ID
  repo = ""               # The repo to store comments

[gitalk]           # Gitalk is a comment system based on GitHub issues. see https://github.com/gitalk/gitalk
  owner = ""              # Your GitHub ID
  repo = ""               # The repo to store comments
  clientId = ""           # Your client ID
  clientSecret = ""       # Your client secret

# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
[valine]
  enable = true
  appId = ''
  appKey = ''
  notify = false  # mail notifier , https://github.com/xCss/Valine/wiki
  verify = false # Verification code
  avatar = ''
  placeholder = ''
  visitor = true

[changyan]
  changyanAppid = ""        # Changyan app id             # 畅言
  changyanAppkey = ""       # Changyan app key

[livere]
  livereUID = ""            # LiveRe UID                  # 来必力

# Isso: https://posativ.org/isso/
[isso]
  enable = false
  scriptSrc = "" # "https://isso.example.com/js/embed.min.js"
  dataAttrs = "" # "data-isso='https://isso.example.com' data-isso-require-author='true'"

[socialOptions]
  email = "sherlockx21@163.com"
  phone = ""
  facebook = ""
  twitter = ""
  github = "https://github.com/Sherlockx21"
  stack-overflow = ""
  instagram = ""
  google-plus = ""
  youtube = "https://www.youtube.com/channel/UCBmqQGuFz4bVo7WcKBYgY4g"
  medium = ""
  tumblr = ""
  linkedin = ""
  pinterest = ""
  stack-exchange = ""
  telegram = ""
  steam = "to finish"
  weibo = ""
  douban = ""
  csdn = ""
  gitlab = ""
  mastodon = ""
  jianshu = ""
  zhihu = ""
  signal = ""
  whatsapp = ""
  matrix = ""
  xmpp = ""
  dev-to = ""
  gitea = ""
  google-scholar = ""

[donationOptions]
  enable = false
  alipay = ""
  wechat = ""
  paypal = ""
  patreon = ""

[copyrightOptions]
  enableCopyrightLink = true
  copyrightLink = ""
  copyrightLinkImage = ""
  copyrightLinkText = "自由转载-非商用"


# possible share name: ["facebook","twitter", "reddit", "linkedin", "tumblr", "weibo", "douban", "line", "pocket", "feedly", "hatena", "pinterest", "delicious", "google"]
[[share]]
  name = "twitter"
[[share]]
  name = "weibo"
[[share]]
  name = "google"
[[share]]
  name = "reddit"
